// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnODrjrPGOhoJ0XcF6KLmPdC--dvspOU',
    appId: '1:406855910302:web:f46f115f442d6b31554c8f',
    messagingSenderId: '406855910302',
    projectId: 'bookmanagementapp-a5268',
    authDomain: 'bookmanagementapp-a5268.firebaseapp.com',
    storageBucket: 'bookmanagementapp-a5268.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqyWTqVwvu31D69smh3mIDXBqSTL07nY',
    appId: '1:406855910302:android:1095fb8dd757e11e554c8f',
    messagingSenderId: '406855910302',
    projectId: 'bookmanagementapp-a5268',
    storageBucket: 'bookmanagementapp-a5268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nhE8H9xg9DnoGSfB8t89UvDOeYF9XGk',
    appId: '1:406855910302:ios:6ee8366b41184358554c8f',
    messagingSenderId: '406855910302',
    projectId: 'bookmanagementapp-a5268',
    storageBucket: 'bookmanagementapp-a5268.appspot.com',
    iosBundleId: 'com.example.bookTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nhE8H9xg9DnoGSfB8t89UvDOeYF9XGk',
    appId: '1:406855910302:ios:6ee8366b41184358554c8f',
    messagingSenderId: '406855910302',
    projectId: 'bookmanagementapp-a5268',
    storageBucket: 'bookmanagementapp-a5268.appspot.com',
    iosBundleId: 'com.example.bookTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxnODrjrPGOhoJ0XcF6KLmPdC--dvspOU',
    appId: '1:406855910302:web:641a6e61efb1ea04554c8f',
    messagingSenderId: '406855910302',
    projectId: 'bookmanagementapp-a5268',
    authDomain: 'bookmanagementapp-a5268.firebaseapp.com',
    storageBucket: 'bookmanagementapp-a5268.appspot.com',
  );
}
